env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
rules: {
  "prettier/prettier": "error",
  "no-underscore-dangle": ["error", {
    "allowAfterThis": true,
    "enforceInMethodNames": false
  }]
}
plugins:
  - prettier
